name: desktop_webview_linux_example
description: "Demonstrates how to use the desktop_webview_linux plugin."
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:

  desktop_webview_linux:
    # When depending on this package from a real application you should use:
    #   desktop_webview_linux: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

  flutter:
    sdk: flutter
  path:
  path_provider:

dev_dependencies:
  carapacik_lints: 1.10.0

flutter:
  uses-material-design: true
